### PR TITLE
Blosc compressor: numThreads serialization fix

### LINKED ISSUE #14: Unexpected keyword argument 'numThreads' when reading Java Zarr with Python
Hi,

When creating Blosc compressor with
```
Compressor compressor = CompressorFactory.create("blosc", "cname", "zstd", "clevel", 9, "blocksize", 0, "shuffle", 1);
```
A new optional parameter for Blosc "nthreads" is added into the .zarray metadata file as
```
"numThreads" : 1
```
And this is what I got when reading this Zarr with the Python API
```
  File "numcodecs\blosc.pyx", line 548, in numcodecs.blosc.Blosc.__init__
TypeError: __init__() got an unexpected keyword argument 'numThreads'
```
<p>

Since 'numThreads' is in metadata files it's not possible anymore to read the resulting Zarr using Python
It's technically a Python error, but since JZarr data has to be compatible with the Python API I think it's more of a Java issue (or did I just do something wrong ?)

### PR DESCRIPTION
**Pull request by sbesson**
Fixes #14  

As described in the accompanying issues, changes in 0.4.0 are causing the addition of the key `numThreads` to the compression map under `.zarray` when using blosc.

This serialization change causes compatibility issues with the expectations of `numcodecs` - see https://numcodecs.readthedocs.io/en/stable/blosc.html#numcodecs.blosc.Blosc. A formal specification of the blosc codec and its supported configuration values is available in the Zarr v3 specification https://zarr-specs.readthedocs.io/en/latest/v3/codecs/blosc/v1.0.html#blosc-codec-version-1-0. Although it's not 100% clear whether this dictionary should be considered as extensible, the number of threads used for compression is a writing concern which is fully independent of the reading/decompression mechanism (which might very well used different number of threads) so it seems incorrect to serialize it in the first place.

Tracking down the source of the issue with @melissalinkert, it was found to be introduced in #4 more specifically via the `getNumThreads` getter method which seems to be serialized under `.zarray` through the `jackson-databind` `ObjectMapper` API. 43cf7f3b4e14627b272faf25bb00b457267a1b4c proposes to remove the getter which suffices to fix the issue while retaining the initial feature.

Opening for initial feedback, it is pretty clear that both the feature and the blosc serialization logic were missing some minimal unit tests which would be great to introduce as part of this PR so that we don't create inadvertent regressions in the future.

### CODE REVIEW

**Review by melissalinkert — COMMENTED** [review]
Works as expected when combined with https://github.com/glencoesoftware/bioformats2raw/pull/203; `.zarray` no longer contains a `numThreads` (or `nthreads`).

One other option might be to keep the getter, and annotate it with `@JsonIgnore` (https://github.com/FasterXML/jackson-annotations/wiki/Jackson-Annotations#property-inclusion). That seemed to work locally at least (but agreed that more unit tests would be helpful in any case).

**Comment by joshmoore** [comment]
- :+1: for the fix (Thanks, @sbesson!)
 - :+1: for the annotation if it works (Thanks, @melissalinkert) so that downstream users don't break (cc: @pedson) though I am confused why this didn't show up for them...

**Comment by sbesson** [comment]
> though I am confused why this didn't show up for them...

As I was wondering why this issue hadn't been reported earlier, I found out the compression constructors are not as strict as in `numcodecs`. At present, any extra key/value can be passed to the factory method/constructor:

```
Compressor compressor = CompressorFactory.create("zlib", "level", 4, "foo", "bar");
```

Support or not for unspecified key/value pairs in the `compressor` key of the JSON is likely a decision that should be enforced at the Zarr specification level. Based on my reading of the current specs,:
- the Zarr v2 specification contains minimal information about the compression format and the supported codecs
- the Zarr v3 specification substantially improves things by providing a official list of the supported codecs and individual specification pages - see https://zarr-specs.readthedocs.io/en/latest/v3/codecs.html
- neither specification defines whether extra parameters not specified in the `Configuration Parameters` section MAY, MIGHT NOT or MUST be stored under the `compressor` key

Given the impact, I would propose to focus the scope of this PR on fixing the serialization issue so that the latest version of the library generates Zarr arrays which metadata is compatible with the assumptions of the other reference libraries.

**Comment by sbesson** [comment]
Last commits should implement @melissalinkert suggestion of using the `@JsonIgnore` annotation which is definitely more elegant than my removal. They also expand the scope of various unit tests to systematically test all core compressions and add a new unit test that specifically test the serialization/deserialization of blosc-compressed arrays.
[a723e05](https://github.com/zarr-developers/jzarr/pull/15/commits/a723e05e6cfde647f678f9977ae162b9bcb7e841) should fail on top of `0.4.0` but passes with the changes above.

While adding new classes came across some inconsistencies/nomenclature questions:
- camel case vs snake case for new classes
- boilerplate and generally copyright for this fork
- the above points at some missing metadata e.g. `organizationName` and `inceptionYear` in the top-level POM in case we would like to update headers across the board

**Review by melissalinkert — APPROVED** [review]

**Comment by joshmoore** [comment]
@pedson: a heads up that once the header on the new (test) file is settled, we'll be getting this released unless you have a problem with it.

**Comment by joshmoore** [comment]
Starting the 0.4.1 🚋
